cc_library(
    name = "bloomfilter",
    hdrs = ["bloomfilter.h"],
    srcs = ["bloomfilter.cc"],
    deps = [
        "//src/libs/fnv",
        "//src/libs/vector",
        "//src/libs/serialize",
        ],
    visibility = ["//visibility:public"],
)
