cc_test(
    name = "serialize_test",
    srcs = [
        "serialize_test.cc",
        "buffer_test.cc"
    ],
    deps = [
        "//src/libs/serialize",
        "//src/libs/utils",
        "//tests:catch"
    ],
)