cc_library(
    name = "document",
    hdrs = ["Document.h"],
    srcs = ["Document.cc"],
    deps = [
        "//src/libs/string",
        "//src/libs/vector",
        "//src/libs/serialize",
        "//src/libs/map",
        "//src/libs/parsedurl"
    ],
    visibility = ["//visibility:public"],
)
