cc_library(
    name = "loaders",
    hdrs = ["loaders.h"],
    srcs = ["loaders.cc"],
    deps = [
        "//src/libs/vector",
        "//src/libs/logger",
        "//src/libs/map",
        "//src/libs/serialize"
    ],

    visibility = ["//visibility:public"],
)
