cc_library(
    name = "parsedurl",
    hdrs = ["ParsedUrl.h"],
    srcs = ["ParsedUrl.cc"],
    deps = [
        "//src/libs/string",
        "//src/libs/utils"
    ],
    visibility = ["//visibility:public"],
)
