cc_library(
    name = "rank",
    hdrs = ["rank.h"],
    srcs = ["rank.cc"],
    deps = [
        "//src/libs/vector",
        "//src/libs/document",
        "//src/libs/string",
        "//src/libs/map"
    ],
    visibility = ["//visibility:public"],
)
