cc_library(
    name = "ranker",
    hdrs = ["ranker.h"],
    srcs = ["ranker.cc"],
    deps = [
        "//src/libs/vector",
        "//src/libs/utils",
        "//src/libs/queryCompiler",
        "//src/libs/index",
        "//src/libs/index/HashTable",
        "//src/libs/frontier/rank",
        "//src/libs/preprocessing/loaders",
        "//src/libs/rank/PriorityQueue",
        "//src/libs/rank",
	"//src/libs/logger"
    ],
    visibility = ["//visibility:public"],
)
