cc_library(
    name = "preprocessedDocument",
    hdrs = [
        "PreprocessedDocument.h",
    ],
    srcs = [
        "PreprocessedDocument.cc",
    ],
    deps = [
        "//src/libs/string",
        "//src/libs/vector",
        "//src/libs/map",
    ],
    visibility = ["//visibility:public"],
)