cc_test(
    name = "frontier_test",
    srcs = ["frontier_test.cc"],
    deps = [
        "//src/libs/frontier",
        "//src/libs/vector",
        "//src/libs/string",
        "//tests:catch"
    ],  
)
