cc_library(
    name = "httpServer",
    hdrs = [
        "HttpServer.h",
        "HttpResponse.h",
        "HttpRequest.h",
    ],
    srcs = [
        "HttpServer.cc",
        "HttpResponse.cc",
        "HttpRequest.cc",
    ],
    deps = [
        "//src/libs/serialize",
        "//src/libs/map",
        "//src/libs/server",
        "//src/libs/utils",
    ],
    visibility = ["//visibility:public"],
)
