apiVersion: v1
kind: Pod
metadata:
  name: frontier
  namespace: default
  labels:
    app: frontier
spec:
  containers:
  - name: frontier
    image: gcr.io/boisboisgo/frontier@sha256:4067c208b715e0a1d8f3b470b601a19d46824a8042513a94c856c26ecfdc44d3
    env:
      - name: BBGLOG
        value: "0"
      - name: BBGEXE
        value: /frontier_main
      - name: BBG_FRONTIER_SIZE
        value: "1000000"
      - name: BBG_FRONTIER_BACKUP
        value: /GoogleDrive/frontier.bak
      - name: BBG_SEED_LIST
        value: /GoogleDrive/seedlist.txt
    resources:
      requests:
        memory: "40Gi"
    securityContext:
      allowPrivilegeEscalation: true
      runAsUser: 0
      privileged: true
      capabilities:
        add: ["SYS_ADMIN"]
    ports:
      - containerPort: 8080
