cc_library(
    name = "queryCompiler",
    hdrs = ["queryCompiler.h"],
    srcs = ["queryCompiler.cc"],
    deps = [
        "//src/libs/string",
        "//src/libs/ISR",
        "//src/libs/naughtyFilter",
        ],
    visibility = ["//visibility:public"],
)
