cc_library(
    name = "HashTable",
    hdrs = [
        "HashTable.h",
    ],
    srcs = ["HashTable.cc"],
    deps = [
        "//src/libs/utils"
    ],
    visibility = ["//visibility:public"],
)
