cc_test(
    name = "PostingList_test",
    srcs = ["postinglist_test.cc"],
    deps = [
        "//src/libs/index/PostingList",
        "//src/libs/index/Post",
        "//src/libs/preprocessedDocument",
        "//tests:catch"
    ],
)
