cc_test(
    name = "urlQueue_test",
    srcs = ["urlQueue_test.cc"],
    deps = [
        "//src/libs/frontier/urlQueue",
        "//src/libs/vector",
        "//src/libs/string",
        "//tests:catch"
    ],  
)
