cc_library(
    name = "Blob",
    hdrs = [
        "Blob.h"
    ],
    srcs = [
        "Blob.cc"
    ],
    deps = [
        "//src/libs/index/HashTable",
        "//src/libs/utils",
        "//src/libs/logger"
        ],
    visibility = ["//visibility:public"],
)
