cc_library(
    name = "robotsManager",
    hdrs = ["robotsManager.h"],
    srcs = ["robotsManager.cc"],
    deps = [
        "//src/libs/utils",
        "//src/libs/map",
        "//src/libs/string",
        "//src/libs/logger",
        "//src/libs/frontier/URL",
        "//src/libs/httpUtils",
        "//src/libs/serialize"
    ],
    visibility = ["//visibility:public"],
)
