cc_library(
    name = "string",
    hdrs = ["string.h"],
    srcs = ["string.cc"],
    deps = [
        "//src/libs/vector",
        "//src/libs/utils",
        "//src/libs/serialize"
    ],
    visibility = ["//visibility:public"],
)
