cc_test(
    name = "queryCompiler_test",
    srcs = ["queryCompiler_test.cc"],
    deps = [
        "//src/libs/queryCompiler",
        "//src/libs/string",
        "//src/libs/vector",
        "//tests:catch",
        "//src/libs/document",
        "//src/libs/preprocessedDocument"
    ]
)
