cc_test(
    name = "Indexer_test",
    srcs = ["indexer_test.cc"],
    deps = [
        "//src/libs/index/Indexer",
        "//src/libs/index/PostingList",
        "//src/libs/index/rankingData",
        "//src/libs/index",
        "//src/libs/preprocessedDocument",
        "//src/libs/string",
        "//src/libs/vector",
        "//src/libs/logger",
        "//src/libs/serialize",
        "//src/libs/gdfs",
        "//src/libs/preprocessing/loaders",
        "//tests:catch"
    ],
)
