cc_library(
    name = "urlQueue",
    srcs = ["urlQueue.cc"],
    hdrs = ["urlQueue.h"],
    deps = [
        "//src/libs/string",
        "//src/libs/parsedurl",
        "//src/libs/frontier/rank",
        "//src/libs/frontier/shuffleQueue"
        ],
    visibility = ["//visibility:public"],
)
