cc_library(
    name = "PriorityQueue",
    hdrs = ["PriorityQueue.h"],
    srcs = ["PriorityQueue.cc"],
    deps = [
        "//src/libs/string",
        "//src/libs/vector",
        "//src/libs/logger",
        ],
    visibility = ["//visibility:public"],
)
