cc_library(
    name = "PostingList",
    hdrs = ["PostingList.h"],
    srcs = ["PostingList.cc"],
    deps = [
        "//src/libs/vector",
        "//src/libs/string",
        "//src/libs/index/rankingData",
        "//src/libs/index/Post",
        "//src/libs/preprocessedDocument"
        ],
    visibility = ["//visibility:public"],
)
