cc_test(
    name = "rpc_test",
    srcs = [
        "rpc_test.cc",
    ],
    deps = [
        "//src/libs/rpc",
        "//tests:catch",
        "//src/libs/utils",
        "//src/libs/string",
        "//src/libs/vector",
    ],
)
