cc_test(
    name = "htmlParser_test",
    srcs = ["htmlParser_test.cc"],
    deps = [
        "//src/libs/document",
        "//src/libs/htmlParser",
        "//tests:catch"
    ],
    data = [
        "boilerplate.html",
        "craigslist.html",
        "GitHub.html",
        "Wikipedia.html"
    ]
)
