cc_library(
    name = "Post",
    hdrs = ["Post.h"],
    srcs = ["Post.cc"],
    deps = [
        "//src/libs/string",
        "//src/libs/index/rankingData",
        "//src/libs/index/LEB128"
        ],
    visibility = ["//visibility:public"],
)
