cc_library(
    name = "shuffleQueue",
    hdrs = ["shuffleQueue.h"],
    srcs = ["shuffleQueue.cc"],
    deps = ["//src/libs/string",
            "//src/libs/queue",
            "//src/libs/utils",
            "//src/libs/frontier/URL",
            ],
    visibility = ["//visibility:public"],
)
