cc_test(
    name = "httpUtils_test",
    srcs = ["httpUtils_test.cc"],
    deps = [
        "//src/libs/httpUtils",
        "//src/libs/string",
        "//tests:catch",
    ],
    data = ["//tests/httpserver"],
)
