cc_library(
    name = "frontier",
    srcs = ["frontier.cc"],
    hdrs = ["frontier.h"],
    deps = [
        "//src/libs/vector",
        "//src/libs/string",
        "//src/libs/frontier/urlQueue",
        "//src/libs/frontier/seen",
        "//src/libs/robotsManager",
        "//src/libs/frontier/URL"
        ],
    visibility = ["//visibility:public"],
)
