cc_library(
    name = "server",
    hdrs = ["Server.h"],
    srcs = ["Server.cc"],
    deps = [
        "//src/libs/logger",
    ],
    linkopts = ["-lpthread"],
    visibility = ["//visibility:public"],
)
