cc_library(
    name = "gdfs",
    hdrs = ["gdfs.h"],
    srcs = ["gdfs.cc"],
    deps = [
        "//src/libs/document",
        "//src/libs/thread",
        "//src/libs/serialize",
        "//src/libs/logger"
        ],
    linkopts = ["-lpthread"],
    visibility = ["//visibility:public"],
)
