cc_library(
    name = "htmlParser",
    hdrs = ["HtmlParser.h"],
    srcs = ["HtmlParser.cc"],
    deps = [
        "//src/libs/document",
        "//src/libs/utils",
        "//src/libs/parsedurl",
        "//src/libs/naughtyFilter"
    ],
    visibility = ["//visibility:public"],
)
