cc_library(
    name = "rankingData",
    hdrs = ["rankingData.h"],
    srcs = ["rankingData.cc"],
    deps = [
        "//src/libs/index/LEB128"
    ],   
    visibility = ["//visibility:public"],
)
