cc_library(
    name = "index",
    hdrs = ["index.h"],
    srcs = ["index.cc"],
    deps = [
        "//src/libs/index/PostingList",
        "//src/libs/map",
        "//src/libs/index/Blob",
        "//src/libs/logger",
        "//src/libs/utils"
        ],
    #linkopts = ["-lpthread"],
    visibility = ["//visibility:public"],
)
