cc_library(
    name = "map",
    hdrs = ["map.h"],
    deps = [
        "//src/libs/vector",
        "//src/libs/fnv",
        "//src/libs/utils",
        "//src/libs/serialize",
        "//src/libs/logger",
        ],
    visibility = ["//visibility:public"],
)
