cc_library(
    name = "ISR",
    srcs = ["ISR.cc"],
    hdrs = ["ISR.h"],
    deps = [
        "//src/libs/index",
        "//src/libs/logger",
        "//src/libs/vector",
        "//src/libs/string",
    ],
    visibility = ["//visibility:public"],
)
