cc_test(
    name = "crawler_test",
    # To run the test, uncomment. Be sure to leave commented when done because
    # this test will break all of CI because this test never ends
    # https://www.youtube.com/watch?v=0U2zJOryHKQ
    #srcs = ["crawler_test.cc"],
    deps = [
        "//src/crawler:crawler_lib",
        "//tests:catch"
    ],
)
