cc_library(
    name = "seen",
    srcs = ["seen.cc"],
    hdrs = ["seen.h"],
    deps = [
        "//src/libs/bloomfilter",
        "//src/libs/vector",
        "//src/libs/fnv",
        "//src/libs/serialize"
        ],
    visibility = ["//visibility:public"],
)
