cc_test(
    name = "shuffleQueue_test",
    srcs = ["shuffleQueue_test.cc"],
    deps = [
        "//src/libs/frontier/urlQueue",
        "//src/libs/frontier/shuffleQueue",
        "//tests:catch"
    ],
)
